name: gen-modeling
channels:
  - pytorch
  - conda-forge
dependencies:
  - python
  - timm
  - pytorch>=2.0.0
  - numpy>=1.23.0
  - pip
  - pip:
    - POT>=0.8.0
    - neptune-client>=1.0.0
    - omegaconf
    - torchdiffeq
    - einops
    - tensorboard
    - wandb
